/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajeev
 */
import java.sql.*;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import sun.rmi.server.UnicastServerRef;
public class exam extends javax.swing.JFrame {
    Connection con;
    Statement stm;
    ResultSet r;
    int n,i;
    void showqst()
{
    try{
   r=stm.executeQuery("select * from QUESTION");
    }
    catch(Exception e)
    {
        System.out.print(e.toString());
    }
}
    public exam() {
            try{
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            con=DriverManager.getConnection("jdbc:derby://localhost:1527/exam","exam","123");
            stm=con.createStatement();
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
        }
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exam");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 10, 100, 30);

        jLabel2.setText("Student id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 60, 60, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(110, 60, 130, 30);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 60, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Question");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 110, 90, 20);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("question");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 160, 490, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Q1");
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(20, 230, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Q2");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(120, 230, 140, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Q3");
        jPanel1.add(jRadioButton3);
        jRadioButton3.setBounds(280, 230, 110, 23);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Q4");
        jPanel1.add(jRadioButton4);
        jRadioButton4.setBounds(390, 230, 120, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(190, 290, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(549, 378));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
          n=Integer.parseInt(jTextField1.getText());
        ResultSet rs=stm.executeQuery("select * from student where id="+n+"");
        if(rs.next())
        {
        showqst();
        r.next();
        jLabel4.setText(r.getString("QUESTION"));
        jRadioButton1.setText(r.getString("CHOICE_1"));
        jRadioButton2.setText(r.getString("CHOICE_2"));
        jRadioButton3.setText(r.getString("CHOICE_3"));
        jRadioButton4.setText(r.getString("CHOICE_4"));
        jRadioButton1.setActionCommand(r.getString("CHOICE_1"));
        jRadioButton2.setActionCommand(r.getString("CHOICE_2"));
        jRadioButton3.setActionCommand(r.getString("CHOICE_3"));
        jRadioButton4.setActionCommand(r.getString("CHOICE_4"));
        }
        else
            JOptionPane.showMessageDialog(this,"Student not exit");
      }
      catch(Exception e)
      {
          System.out.println(e.toString());
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
         ButtonModel m=buttonGroup1.getSelection();
          if(buttonGroup1.isSelected(m))
        {
        String q=buttonGroup1.getSelection().getActionCommand();
        if(q.equals(r.getString("RIGHT_ANS")))
        {
            JOptionPane.showMessageDialog(this,"Right Anser");
            i++;
        }
        else
            JOptionPane.showMessageDialog(this,"Worng Anser");
        m=null;
        buttonGroup1.clearSelection();
        }
        r.next();
        jLabel4.setText(r.getString("QUESTION"));
        jRadioButton1.setText(r.getString("CHOICE_1"));
        jRadioButton2.setText(r.getString("CHOICE_2"));
        jRadioButton3.setText(r.getString("CHOICE_3"));
        jRadioButton4.setText(r.getString("CHOICE_4"));
        jRadioButton1.setActionCommand(r.getString("CHOICE_1"));
        jRadioButton2.setActionCommand(r.getString("CHOICE_2"));
        jRadioButton3.setActionCommand(r.getString("CHOICE_3"));
        jRadioButton4.setActionCommand(r.getString("CHOICE_4"));
      }
      catch(Exception e)
      {
          System.out.println(e.toString());
          JOptionPane.showMessageDialog(this,"Your exam is complete");
           JOptionPane.showMessageDialog(this,"Your marks is"+i);
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
